apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  selector:
    app: brain-tasks-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000       
      targetPort: 3000  



