version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047447426147.dkr.ecr.us-east-1.amazonaws.com
      
      - echo Logging in to Docker Hub to avoid rate limit...
      - DOCKERHUB_USERNAME=$(aws ssm get-parameter --name /dockerhub/username --region us-east-1 --query "Parameter.Value" --output text)
      - DOCKERHUB_PASSWORD=$(aws ssm get-parameter --name /dockerhub/password --with-decryption --region us-east-1 --query "Parameter.Value" --output text)
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app:latest .
      - docker tag brain-tasks-app:latest 047447426147.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 047447426147.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - echo Deploying to EKS...
      - aws eks --region us-east-1 update-kubeconfig --name brain-tasks-cluster
      - kubectl apply -f brain-tasks-deployment.yaml
      - kubectl apply -f brain-tasks-service.yaml
